import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

//Components
import Header from '../components/pageHeader'
import Footer from '../components/pageFooter'

const Home = () => {
  return (
    //Container for page
    <div className={styles.container}>

      {/**Header displayed on tab/ favicon*/}
      <Head>
        <title>Best Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/**Container for body of page */}
      <main className={styles.main}>

        {/**Header component */}
        <Header/>
        
        {/**Subtitle */}
        <div className={styles.subtitleContainer}>

          <p className={styles.subtitle}>
            Keep track of current news about sports, health, technology, and business
          </p>
          
        </div>
        
        {/**Underline */}
        <span className={styles.underline}></span>

        {/**Image */}
        <div className={styles.imageContainer}>
          <Image
            src= "/finalNews.png"

            width = {300}
            height = {300}
         
            />
        </div>

        {/**Button to next page */}
        <Link href="/news">

          <a className={styles.button}>

              <text className={styles.buttonText}>
                Get Started
              </text>

          </a>
         
        </Link>
          
      </main>

        {/**Footer component */}
        <Footer/>
      
    </div>
  )
}

export default Home
